android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# FullTank Default Build Properties (Override in your local ~/.gradle/gradle.properties or local.properties)
FULLTANK_SERVER_URL=
FULLTANK_SECRET_TOKEN=demo_secret_token
FULLTANK_SPREADSHEET_URL=
